apiVersion: v1
kind: Pod
metadata:
  name: sailing
spec:
  containers:
  - name: sailing
    image: donaldduck70/sapsailing:docker-201812052304
    imagePullPolicy: Always
    ports:
    - containerPort: 8888
      name: http-port
    - containerPort: 14888
      name: telnet-port
    resources:
      requests:
        memory: "3Gi"
        cpu: "250m"
      limits:
        memory: "8Gi"
        cpu: "500m"
    env:
    - name: MONGODB_URI
      value: mongodb://mongodb-mongodb-replicaset-0.mongodb-mongodb-replicaset,mongodb-mongodb-replicaset-1.mongodb-mongodb-replicaset,mongodb-mongodb-replicaset-2.mongodb-mongodb-replicaset/docker
    livenessProbe:
      httpGet:
        path: /
        port: http-port
      initialDelaySeconds: 10
      periodSeconds: 30
  imagePullSecrets:
  - name: regcred
