apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-master-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: {{ template "sapsailing-app-name" . }} 
    role: {{ .Values.master.role }}
    environment: {{ .Values.environment }}
  ports:
    - port: 8888
      targetPort: http-port
