apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapsailing-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sapsailing-operator
  template:
    metadata:
      labels:
        name: sapsailing-operator
    spec:
      serviceAccountName: sapsailing-operator
      containers:
        - name: sapsailing-operator
          # Replace this with the built image name
          image: alstolten/sapsailing-operator:0.1.16
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "sapsailing-operator"
      imagePullSecrets:
        - name: dockerhubsecret
