# Default values for sap-sailing-analytics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Value of the "app"-tag. Currently used as identifier of a set (similar as a dedicated server setup). If not specified here defaults to the helm release name. It is also used as the mongodb name.
#app: test

# Specify environment
environment: sailing

replicaCount: 1

# Image used to build
image:
  repository: donalduck70/sapsailing
  tag: latest
  pullPolicy: always

# Name of the Kubernetes secret that should be used to pull the images
imagePullSecret: dockerhubsecret

### Environment setup
## General
# Mongodb: specify the name of the service that exposes the mongodb replicaset and the replica set name.
mongodbService: mongo-live-rs-client
replicaSetName: rs0

# RabbitMq: specifiy the name of the service that exposes the rabbitMq
rabbitmq: rabbitmq
# Master
master:
  role: sailing-master

