stages:
  - deps
  - build
  - test
  - posttest
  - distro

before_script:
  - pwd
  - source ${CI_PROJECT_DIR}/env.sh
  - echo "GOPATH is set to ${GOPATH}"
  - cp ~/.ssh/id_rsa ${CI_PROJECT_DIR}/configs/secrets/id_rsa
  - cp ~/.ssh/id_rsa.pub ${CI_PROJECT_DIR}/configs/secrets/id_rsa.pub
  - cp ~/conf_aws.json ${CI_PROJECT_DIR}/configs/secrets/conf_aws.json
  - make clean

makedistro:
  stage: distro
  artifacts:
    paths:
      - orchestration*.tgz
    expire_in: 1 month
  script:
    - echo "Creating distribution"
    - pwd
    - rm -rf ${CI_PROJECT_DIR}/bin
    - mkdir -p ${CI_PROJECT_DIR}/bin
    - make build
    - make distro

makedeps:
  stage: deps
  script:
    - echo "Getting Dependencies"
    - pwd
    - make dep

makebuild:
  stage: build
  artifacts:
    paths:
      - bin
    expire_in: 1 week
  script:
    - echo "Build Started"
    - pwd
    - rm -rf ${CI_PROJECT_DIR}/bin
    - mkdir -p ${CI_PROJECT_DIR}/bin
    - make build

testbuild:
  stage: test
  artifacts:
    expire_in: 1 week
    paths:
      - ${CI_PROJECT_DIR}/testlogs
  script:
    - echo "Test Started"
    - pwd
    - rm -rf ${CI_PROJECT_DIR}/testlogs
    - mkdir -p ${CI_PROJECT_DIR}/testlogs
    - make test

checktestlog:
  stage: posttest
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - ${CI_PROJECT_DIR}/testlogs
  script:
    - echo "check Tests"
    - pwd
    - make checktest
    - make vet
    - make testcover
  when: on_success
