name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    #defaults:
    #  run:
    #    working-directory: ./scripts
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Install JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '8'
      #- name: Make the script files executable
      #  run: chmod +x my-script.sh my-other-script.sh
      - shell: bash
        run: |
          ./configuration/buildAndUpdateProduct.sh -a build 2>&1 | tee build.log
      #- name: Run the scripts
      #  run: |
      #    ./my-script.sh
      #    ./my-other-script.sh
