name: build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Install JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '8'
          mvn-toolchain-id: 'JavaSE-1.8'
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: 4.4
      - name: Start RabbitMQ
        uses: namoshek/rabbitmq-github-action@v1
        with:
          version: '3.8.9'
          ports: '5672:5672'
      - shell: bash
        run: |
          ./configuration/buildAndUpdateProduct.sh -a build 2>&1 | tee build.log
      - shell: bash
        run: |
          ./configuration/buildAndUpdateProduct.sh -u -L release
      - uses: actions/upload-artifact@v4
        with:
            name: release
            path: dist/**/*
            retention-days: 30
