name: Merge main branch into docker-17 after successful build
on:
  workflow_run:
    workflows: [release]
    types: [completed]
    branches: [main]
  workflow_dispatch: {}
jobs:
  merge-main-into-docker-17:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: docker-17
          fetch-depth: 0  # fetch the whole thing to make sure the histories merge
      - name: Merge main into docker-17
        uses: devmasx/merge-branch@master
        env:
          GH_TOKEN: ${{ secrets.REPO_TOKEN_FOR_MERGE_AND_PUSH }}
        with:
          type: now
          from_branch: main
          target_branch: docker-17
          message: Auto-merging main into docker-17 after successful release build
          github_token: ${{ secrets.REPO_TOKEN_FOR_MERGE_AND_PUSH }}
