name: Merge master from sapsailing.com
on:
  schedule:
    - cron: "*/5 * * * *"   # every five minutes
  workflow_dispatch: {}
jobs:
  merge-master-from-sapsailing-com:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create SSH key and fetch
        shell: bash
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_FOR_TRAC_SAPSAILING_COM }}" >~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          git remote add sapsailing ssh://trac@sapsailing.com/home/trac/git
          git remote -v
          GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" git fetch sapsailing
          git fetch origin
          git merge sapsailing/master
          git push
