name: play-with-docker
on:
  workflow_dispatch: {}
jobs:
  play-with-docker-job:
    #runs-on: ubuntu-latest-64cpu
    #runs-on: ubuntu-latest-4cpu
    runs-on: ubuntu-latest
    steps:
#      - name: Login to Quay.io
#        uses: docker/login-action@v3
#        with:
#          registry: docker.sapsailing.com
#          username: ${{ secrets.DOCKER_SAPSAILING_COM_USERNAME }}
#          password: ${{ secrets.DOCKER_SAPSAILING_COM_PASSWORD }}
      - name: Build & push Docker image
        uses: docker/build-push-action@v6
        with:
          image: test
          tags: v0.1, latest
          registry: docker.sapsailing.com
          dockerfile: docker/Dockerfile
          context: docker/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
